# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic (*sub-namespace, see below)
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

twist_mux:
  ros__parameters:
    topics:
      follow:
        topic: follow_cmd_vel
        timeout: 0.5
        priority: 200
      joystick:
        topic: joystick_cmd_vel
        timeout: 0.5
        priority: 150
    locks:
      # follow:
      #   topic: follow_bool
      #   timeout: 0.0
      #   priority: 100
      # joystick:
      #   topic: teleop_bool
      #   timeout: 0.0
      #   priority: 0
      e_stop:
        topic: idle_bool
        timeout: 0.0
        priority: 255